version: '3.0'
services:
  app:
    container_name: 'apiBooks'
    build: .
    volumes:
      - '.:/apiBooks'
      -  '/apiBooks/node_modules'
    ports:
      - '3000:3000'
    command: 'npm run dev'
